<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.0 INSTALLER - Saturday 22nd of September 2012 04:34:28 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://test.grumbleonline.com/php/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => false
			),

			"AOL"  => array ( 
				"enabled" => false 
			),

			"Yahoo" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "468843861206.apps.googleusercontent.com", "secret" => "9eIQxAMEkMBH5hZkRKse6fur" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "178795128911821", "secret" => "973843b517903adde995f4f6b7f2a206" )
			),

			"Twitter" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "lh9TnaksHp9rEEFFPlKnvQ", "secret" => "48mnmGTShZsHldqVhs0DuYx73XQvpIHHP6qLp4me4E" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
